### ISSUE TITLE
No wx2pfpx.exe file after installation

### ISSUE THREAD

**Issue by Aeroplanino83** [aloys-c/wx2pfpx#14]
Installation failed: File wx2pfpx.exe missing after installation. Folder "dist" (which is source for wx2pfpx.exe) missing for installation script.

**Comment by aloys-c** [comment]
Hi,

can you give details on what you are trying to do ? Are you trying to compile the code ?

There is a .zip archive with the final version available, no installation it’s a standalone .exe. Also it’s possible your antivirus deleted it, try disabling it temporarily or whitelisting the .exe…

**Comment by Aeroplanino83** [comment]
Hi, aloy-c! 
Yeah, it was a problem with outdated zip software on my side. My apologies for that..
This issue solved.
