### ISSUE TITLE
Problem with weather data

### ISSUE THREAD

**Issue by denadin23** [aloys-c/wx2pfpx#3]
Hello aloys-c!
Thanks a lot for your program) It`s really useful for my flight planning. Nevertheless, I have a problem with weather data. Once I wanted to plan my flight. (Of course I launched the wx2pfpx program and updated data but in the PFPX the data was outdated) How can I fix this? I`ve also attached some screenshots. (The screenshot was taken on the 30th of October)
Cheers!
![Снимок](https://user-images.githubusercontent.com/116992115/198862662-ae10fe3b-eb72-4909-914f-3e83d0f4d041.JPG)

**Comment by aloys-c** [comment]
Hi !

When updating the data, the script will query the administration server which will send the last available data. My guess is the server was either down or not up-to-date…

**Comment by denadin23** [comment]
I hope that all will be fine soon)
