### ISSUE TITLE
wx2pfpx unable to download weather due to aviationweather.gov API changes 

### ISSUE THREAD

**Issue by PinkPony89** [aloys-c/wx2pfpx#7]
Hello Aloys,

As of 16OCT23 aviationweather.gov implemented API changes. As a result wx2pfpx cannot download METAR/TAF data anymore. It gets gets stucks on "downloading last weather reports"

https://aviationweather.gov/help/#url

https://aviationweather.gov/data/api/

Would it be possible for you to update the application?

PFPX is also no longer downloading METAR/TAF. It is unclear at this time if they will update their application :(

**Comment by aloys-c** [comment]
Hi,

I don't have much time at the moment to take care of the issue, If you're motivated I would suggest finding someone that can fork the repo and continue maintaining it.

**Comment by PinkPony89** [comment]
Hi Aloys, 

Thankfully I was able to fix it very easily. I did not have any prior python experience so I just had to quickly learn out how to install pyinstaller. Thank you for including the package.cmd, made things a lot easier!

Here is the fix:

 In **main.py** I updated the URL header:
 
from: https://aviationweather.gov/adds/dataserver_current/ 
to: **https://aviationweather-cprk.ncep.noaa.gov/adds/dataserver_current/**

 In **utils/parse_station.py**

from: https://aviationweather.gov/adds/dataserver_current/ 
to: **https://aviationweather.gov/adds/dataserver_current/** 

I compiled this as **v2.6** feel free to share on your GitHub 



[wx2pfpx2.6.zip](https://github.com/aloys-c/wx2pfpx/files/13063949/wx2pfpx2.6.zip)

**Comment by aloys-c** [comment]
Hi PinkPony,

I just quickly checked your version and the fix seems to work just fine ! 

That's a lot of luck the data format hasn't changed and it's only the URL, I was afraid this would lead to hours rewriting the code handling the data... Anyway congrats on your update !

If you don't mind, you can make a "Pull request" on my repo so that we merge our codes and you become a contributor on my repo too :)

**Comment by aloys-c** [comment]
Thanks to PinkPony89 for the fix, issue is now solved

**Comment by PinkPony89** [comment]
> Thanks to PinkPony89 for the fix, issue is now solved

Thank you for confirming @aloys-c 

Its still unclear if the METAR/TAF observations/forecasts which are now hosted at https://aviationweather-cprk.ncep.noaa.gov/dataserver will remain available. According to the new https://aviationweather.gov/ website the Text Data Server has been replaced by the NOAA API (as of 16OCT23).

It is possible that the https://aviationweather-cprk.ncep.noaa.gov/adds/dataserver_current/ is only a temporary fallback to the old Text Data Server? I cannot find any information on the NOAA website to confirm or deny this. 

In any case, as of of the time of this post the METAR/TAF observations/forecasts available under https://aviationweather-cprk.ncep.noaa.gov/adds/dataserver_current/ remain available and up to date. 

If you have any time in the future, would you mind looking into new API links and possibly consider implementing them?

These are the direct links to the METAR and TAF .xml files (from NOAA API **Cache**) https://aviationweather.gov/data/api/
https://aviationweather.gov/data/cache/metars.cache.xml
https://aviationweather.gov/data/cache/taf.cache.xml

I believe the current wx2pfpx code requires some change to read the new Cache .xml files as the /httpparam?datasource=metars&requestType=retrieve&fields=raw_text,station_id&format=xml&mostRecentForEachStation=constraint&hoursBeforeNow=3&stationString= no longer functions with the Cache .xml files.

**Comment by twSimulations** [comment]
WX2PFPX seems not to work (again). It doesn't to anything when clicking on the "Download data" button

**Comment by aloys-c** [comment]
> WX2PFPX seems not to work (again). It doesn't to anything when clicking on the "Download data" button

Hi,

As a reminder this is a project based on volunteer work, and this chat is not a customer helpline, at least saying « hello » would be appreciated !

I’ll have a look tomorrow, expect a possible fix in the coming days…

**Comment by aloys-c** [comment]
The API has been updated with the most recent version available. You can download the new version 2.6.3 in the main folder... Hopefully this lasts !
